# Generated by Django 4.0.10 on 2024-12-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
