# Generated by Django 4.0.10 on 2024-12-24 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salon', '0004_beautician_booking_customersalon_membershipscheme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beautician',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='beautician',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='beautician',
            name='LastName',
        ),
        migrations.AddField(
            model_name='beautician',
            name='linked_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
