# Generated by Django 4.0.10 on 2024-12-24 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salon', '0005_remove_beautician_email_remove_beautician_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='membershiptype',
            name='membership_scheme',
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='billing_period',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='MembershipScheme',
        ),
        migrations.AddField(
            model_name='membershipservice',
            name='membership_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.membershiptype'),
        ),
        migrations.AddField(
            model_name='membershipservice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.service'),
        ),
        migrations.AddField(
            model_name='membershipservice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
