# Generated by Django 4.0.10 on 2024-12-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_membershipservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLoadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True)),
                ('context', models.TextField(blank=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.RenameField(
            model_name='beautician',
            old_name='Phone',
            new_name='phone',
        ),
    ]
