# Generated by Django 4.0.10 on 2024-12-26 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_dataloadmodel_rename_phone_beautician_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersalon',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customersalon',
            old_name='FirstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customersalon',
            old_name='LastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='customersalon',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='cost_price',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='price',
            new_name='cost_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='entity_type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='entity_type',
        ),
        migrations.AddField(
            model_name='membershipservice',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.variant'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='variant_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.category'),
        ),
        migrations.AddField(
            model_name='variant',
            name='sales_price',
            field=models.FloatField(default=0.0),
        ),
    ]
