# Generated by Django 4.0.10 on 2025-01-06 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='ttl_hrs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='ttl_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.booking'),
        ),
    ]
