# Generated by Django 4.0.10 on 2025-01-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0011_service_ttl_hrs_service_ttl_min_session_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='beauticians',
            field=models.ManyToManyField(through='salon.BookingService', to='salon.beautician'),
        ),
        migrations.AddField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(through='salon.BookingService', to='salon.service'),
        ),
    ]
