# Generated by Django 4.0.10 on 2025-01-09 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0013_media_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='session',
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='close_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='open_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='pos_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='status_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.sessionstatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.booking'),
        ),
    ]
