# Generated by Django 4.0.10 on 2025-01-15 09:37

from django.db import migrations, models
import django.db.models.deletion
import salon.models.document


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0014_remove_order_session_bookingservice_close_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.FileField(upload_to='upload/salon/document', validators=[salon.models.document.validateDocument]),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='salon.category'),
        ),
    ]
