# Generated by Django 4.0.10 on 2025-01-16 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0018_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='salon.customersalon'),
        ),
    ]
