# Generated by Django 4.0.10 on 2025-01-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0019_userfile_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersalon',
            name='profile_image_unique_id',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
