# Generated by Django 4.0.10 on 2025-01-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0020_customersalon_profile_image_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersalon',
            name='profile_image_unique_id',
        ),
    ]
