# Generated by Django 4.0.10 on 2025-01-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0021_remove_customersalon_profile_image_unique_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='sub_total',
            new_name='subtotal',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='variant_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('noshow', 'No show')], default='new', max_length=16),
        ),
    ]
