# Generated by Django 4.0.10 on 2025-01-21 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0022_rename_sub_total_orderdetail_subtotal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingservice',
            old_name='status_id',
            new_name='status',
        ),
    ]
