# Generated by Django 4.0.10 on 2025-01-22 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0023_rename_status_id_bookingservice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersalon',
            name='address',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='salon.customersalon'),
        ),
    ]
