# Generated by Django 4.0.10 on 2025-01-22 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0023_rename_status_id_bookingservice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.booking'),
        ),
    ]
