# Generated by Django 4.0.10 on 2025-01-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0024_queue_booking'),
        ('salon', '0025_alter_booking_customer'),
    ]

    operations = [
    ]
