# Generated by Django 4.0.10 on 2025-02-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0028_alter_orderdetail_order_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersalon',
            name='email',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
