# Generated by Django 4.0.10 on 2025-02-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0029_alter_customersalon_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautician',
            name='address',
            field=models.TextField(default=None, null=True),
        ),
    ]
