# Generated by Django 4.0.10 on 2025-02-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_ehr'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehr',
            name='phone_number',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
