# Generated by Django 4.0.10 on 2024-10-08 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
