# Generated by Django 4.0.10 on 2024-11-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtf', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('ui', models.JSONField(blank=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
