# Generated by Django 4.0.10 on 2024-12-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtf', '0005_user_organizations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organizations',
        ),
    ]
