# Generated by Django 4.0.10 on 2024-12-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtf', '0007_role_userorganizationrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
