# Generated by Django 4.0.10 on 2024-12-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtf', '0008_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_code',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
