# Generated by Django 4.0.10 on 2024-12-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtf', '0010_userorganization_delete_userorganizationrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='identifier',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
