# Generated by Django 4.0.10 on 2025-01-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('authtf', '0011_role_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(through='authtf.UserOrganization', to='organization.organization'),
        ),
    ]
