# Generated by Django 4.0.10 on 2025-01-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtf', '0015_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
