# Generated by Django 4.0.10 on 2025-01-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtf', '0017_sociallogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallogin',
            name='profile_image',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
