# Generated by Django 4.0.10 on 2025-04-15 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0030_adaccesscode_hear_about'),
        ('authtf', '0022_user_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_ethnicity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_ethnicity', to='ad.ethnicity'),
        ),
    ]
