# Generated by Django 4.0.10 on 2024-12-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
