# Generated by Django 4.0.10 on 2024-11-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextcard',
            name='graph_attributes',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
