# Generated by Django 4.0.10 on 2024-11-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_contextcard_graph_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextcard',
            name='graph_attributes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
