# Generated by Django 4.0.10 on 2024-12-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_contextcard_graph_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageOut', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
