# Generated by Django 4.0.10 on 2024-12-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_replymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.JSONField(blank=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
