# Generated by Django 4.0.10 on 2025-02-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_tokenmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenModel',
        ),
    ]
