# Generated by Django 4.0.10 on 2025-04-18 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('card', '0006_delete_tokenmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextcard',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organization'),
        ),
    ]
