# Generated by Django 4.0.10 on 2025-02-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_specialization_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='postal_code',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
    ]
