# Generated by Django 4.0.10 on 2025-03-04 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ad', '0007_insuranceprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('booking_date_time', models.DateTimeField()),
                ('insurance_file_uuid', models.CharField(default=None, max_length=36, null=True)),
                ('custom_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='new', max_length=16)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organization')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_bookings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ad_patient_booking',
            },
        ),
    ]
