# Generated by Django 4.0.10 on 2025-03-06 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0011_aduserfile_admedia_addocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchathistory',
            name='booking_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_id_rel', to='ad.patientbooking'),
        ),
        migrations.AlterField(
            model_name='addocument',
            name='file_path',
            field=models.FileField(upload_to='upload/ad/document'),
        ),
    ]
