# Generated by Django 4.0.10 on 2025-03-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0012_userchathistory_booking_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchathistory',
            old_name='booking_id',
            new_name='booking',
        ),
    ]
