# Generated by Django 4.0.10 on 2025-03-11 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
        ('ad', '0013_rename_booking_id_userchathistory_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceprovider',
            name='speciality',
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='doctor',
            field=models.ManyToManyField(related_name='insurance_providers', to='ad.doctor'),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='logo',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('doctor', models.ManyToManyField(related_name='languages', to='ad.doctor')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_trainings', to='ad.doctor')),
            ],
            options={
                'db_table': 'ad_education_training',
            },
        ),
    ]
