# Generated by Django 4.0.10 on 2025-03-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0014_insurancerecord'),
        ('ad', '0014_remove_insuranceprovider_speciality_and_more'),
    ]

    operations = [
    ]
