# Generated by Django 4.0.10 on 2025-03-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0015_merge_20250311_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
