# Generated by Django 4.0.10 on 2025-03-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0016_doctor_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='appointment_cost',
            field=models.FloatField(default=None, null=True),
        ),
    ]
