# Generated by Django 4.0.10 on 2025-03-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0017_doctor_appointment_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='source',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
