# Generated by Django 4.0.10 on 2025-03-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0018_doctor_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbooking',
            name='postal_code',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
    ]
