# Generated by Django 4.0.10 on 2025-03-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0022_patientqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='data_x',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
