# Generated by Django 4.0.10 on 2025-03-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0023_notification_data_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientqueue',
            name='is_rescheduled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
