# Generated by Django 4.0.10 on 2025-03-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0025_gender_ethnicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbooking',
            name='report_file_uuid',
            field=models.CharField(default=None, max_length=36, null=True),
        ),
    ]
