# Generated by Django 4.0.10 on 2025-03-31 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0026_patientbooking_report_file_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('flag_new', models.BooleanField(default=False)),
                ('flag_cancelled', models.BooleanField(default=False)),
                ('flag_confirmed', models.BooleanField(default=False)),
                ('flag_reminder', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_status', to='ad.patientbooking')),
            ],
            options={
                'db_table': 'ad_notification_status',
            },
        ),
    ]
