# Generated by Django 4.0.10 on 2025-04-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0027_notificationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchathistory',
            name='content_destination',
            field=models.TextField(default=None, null=True),
        ),
    ]
