# Generated by Django 4.0.10 on 2025-04-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0028_userchathistory_content_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbooking',
            name='insurance_provider',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='patientbooking',
            name='member_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='patientbooking',
            name='subscription_number',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
