# Generated by Django 4.0.10 on 2025-04-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0029_patientbooking_insurance_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccesscode',
            name='hear_about',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
