# Generated by Django 4.0.10 on 2025-04-21 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ad', '0030_adaccesscode_hear_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default=None, null=True)),
                ('lattitude', models.FloatField(default=None, null=True)),
                ('longitude', models.FloatField(default=None, null=True)),
                ('logo_uuid', models.CharField(default=None, max_length=36, null=True)),
                ('city', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labs', to='ad.city')),
                ('country', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labs', to='ad.country')),
                ('insurance_providers', models.ManyToManyField(related_name='labs', to='ad.insuranceprovider')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organization')),
                ('state', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labs', to='ad.state')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
