# Generated by Django 4.0.10 on 2025-04-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0031_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='address',
            field=models.TextField(default=None, null=True),
        ),
    ]
