# Generated by Django 4.0.10 on 2025-05-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0033_referralcode_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phone_official',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
