# Generated by Django 4.0.10 on 2025-05-05 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
        ('ad', '0033_referralcode_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('keywords', models.JSONField()),
                ('chat_history_category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_keywords', to='ad.chathistorycategory')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ad_chat_keyword',
            },
        ),
    ]
