# Generated by Django 4.0.10 on 2025-05-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0034_chatkeyword'),
        ('ad', '0034_doctor_phone_official'),
    ]

    operations = [
    ]
