# Generated by Django 4.0.10 on 2025-05-06 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ad', '0035_merge_0034_chatkeyword_0034_doctor_phone_official'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='medical_type',
            field=models.TextField(default=None, max_length=36, null=True),
        ),
        migrations.CreateModel(
            name='SpecializationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.TextField()),
                ('slug', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ad_specialization_category',
            },
        ),
        migrations.AddField(
            model_name='specialization',
            name='specialization_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad.specializationcategory'),
        ),
    ]
