# Generated by Django 4.0.10 on 2025-05-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0036_specialization_medical_type_specializationcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='medical_type',
        ),
        migrations.AddField(
            model_name='specializationcategory',
            name='medical_type',
            field=models.TextField(default=None, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='specializationcategory',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
