# Generated by Django 4.0.10 on 2025-04-24 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargebeeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('subscription_id', models.CharField(default=None, max_length=36, null=True, verbose_name='Subscription Id from chargebee')),
                ('metadata', models.JSONField(default=None, null=True, verbose_name='Subscription related data from Chargebee')),
                ('chargebee', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscription.chargebee')),
            ],
            options={
                'db_table': 'payment_chargebee_subscription',
            },
        ),
    ]
